FreeBSD_task:
  matrix:
    env:
      SSL: openssl
    env:
      # base openssl
      SSL:
  matrix:
    freebsd_instance:
      image_family: freebsd-13-1
  prepare_script:
    - pkg install -y pkgconf cmake git libsodium cpu_features $SSL
    - git submodule update --init --recursive
  configure_script:
    - env CFLAGS="-I/usr/local/include/cpu_features" ./configure
  build_script:
    - make -j $(sysctl -n hw.ncpu || echo 4) -C build
  test_script:
    - ldd build/vpnserver
    - .ci/memory-leak-test.sh
    - .ci/vpntools-check.sh
